name: 'AWS Authentication'
description: 'Assumes a role in AWS'
input:
  role-to-assume:
    description: 'The role to assume'
    required: true
  region:
    description: 'The region to use'
    required: false
    default: 'us-east-1'
  session-name:
    description: 'The session name'
    required: false
    default: 'GitHubActions'
outputs:
  ecr-registry:
    description: 'ECR registry'
    value: ${{ steps.login-ecr.outputs.registry }}
runs: 
  using: 'composite'
  steps:
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: ${{ inputs.session-name }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2